services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: #endpoint
      WORDPRESS_DB_USER: #username
      WORDPRESS_DB_PASSWORD: #password
      WORDPRESS_DB_NAME: #db_name
    volumes:
      - /wordpress:/var/www/html
    networks:
      - tunel

networks:
  tunel:
    driver: bridge
