services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: #endpoint rds
      WORDPRESS_DB_USER: #username rds
      WORDPRESS_DB_PASSWORD: #senha rds
      WORDPRESS_DB_NAME: #nome do bd rds
    volumes:
      - /wordpress:/var/www/html
    networks:
      - tunel

networks:
  tunel:
    driver: bridge
